name: Feature to Develop PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop

jobs:
  check-feature-pr:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Check PR from feature to develop
        run: echo "PR de feature para develop detectado. Pronto para revis√£o."