name: Version on Develop

on:
  push:
    branches:
      - develop

jobs:
  version-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '24'
      - run: npm install --save-dev semantic-release @semantic-release/exec
      - name: Get next SNAPSHOT version
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx semantic-release --dry-run > output.log
          VERSION=$(grep -oP 'Published release \K[0-9]+\.[0-9]+\.[0-9]+' output.log | tail -1)
          SNAPSHOT_VERSION="${VERSION}-SNAPSHOT"
          echo "version=$SNAPSHOT_VERSION" >> $GITHUB_OUTPUT
      # Aqui vocÃª pode adicionar build/publish do pacote com o sufixo -SNAPSHOT
