name: Develop to Release PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - release/**

jobs:
  check-develop-pr:
    if: github.base_ref == 'release' && github.head_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Check PR from develop to release
        run: echo "PR de develop para release detectado. Pronto para revis√£o."